config/routes.rb
Vote4Me::Application.routes.draw do
  resources :ideas do
    member { post :vote }
  end

  root to: "welcome#index"
  devise_for :users

end

app/models/idea.rb
class Idea < ActiveRecord::Base

  belongs_to :user
  has_many :idea_votes, dependent: :destroy

  attr_accessible :title, :description

  def self.by_votes
    select('ideas.*, sum(coalesce(value, 0)) as votes').
    joins('left join idea_votes on ideas.id = idea_votes.idea_id').
    group('ideas.id').
    order('votes desc')
  end

  def votes
    read_attribute(:votes) || idea_votes.sum(:value)
  end

  def user_vote(user)
    self.idea_votes.where('user_id = ?', user.id)
  end

end

app/models/idea_vote.rb
class IdeaVote < ActiveRecord::Base

  attr_accessible :value, :idea, :idea_id

  belongs_to :user
  belongs_to :idea

  validates_uniqueness_of :idea_id, scope: :user_id
  #validates_inclusion_of :value, in: Array(0..3)
  validate :ensure_not_author

  def ensure_not_author
    errors.add :user_id, " is the author of the idea" if idea.user_id == user_id
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :name, :password, :encrypted_password

  has_many :ideas, dependent: :destroy
  has_many :idea_votes, dependent: :destroy

  def total_votes
    IdeaVote.joins(:idea).where(ideas: {user_id: self.id}).sum('value')
  end

  # TODO: check here if user's budget allows the voting
  def can_vote_for?(idea)
    vote = idea_votes.build(idea_id: idea.id)
    vote.value = 0
    vote.valid?
  end

  def can_edit?(user)
    self == user
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_filter :authenticate_user!, except: [:index]
  before_action :set_idea, only: [:show, :edit, :update, :destroy, :vote]

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.by_votes
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
    #get existing vote or create a new one and initialize value to 0
    @idea_vote = current_user_vote || IdeaVote.new(value: 0)
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = current_user.ideas.new(idea_params)
    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render action: 'show', status: :created, location: @idea }
      else
        format.html { render action: 'new' }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url }
      format.json { head :no_content }
    end
  end

  def vote
    #get existing vote or create a new one
    vote = current_user_vote || current_user.idea_votes.new
    vote.idea_id = params[:id]
    vote.value = params['voting_score'].to_i
    if vote.save
      redirect_to :back, notice: "Thank you for voting."
    else
      #Todo: check what is the error and show accordingly
      redirect_to :back, alert: "Unable to vote, #{vote.errors.full_messages.first}."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    def current_user_vote
      @idea.user_vote(current_user).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:title, :description, :user_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foundation_helper.rb
module FoundationHelper
  # <div class="alert-box [success alert secondary]">
  #   This is an alert box.
  #   <a href="" class="close">&times;</a>
  # </div>
  DEFAULT_KEY_MATCHING = {
    :alert     => :alert,
    :notice    => :success,
    :info      => :standard,
    :secondary => :secondary,
  }

  def display_flash_messages(key_matching = {})
    key_matching = DEFAULT_KEY_MATCHING.merge(key_matching)

    flash.inject "" do |message, (key, value)|
      message += content_tag :div, :data => { :alert => "" }, :class => "alert-box radius #{key_matching[key] || :standard}" do
        (value + link_to("&times;".html_safe, "#", :class => :close, title: I18n.t('close'))).html_safe
      end
    end.html_safe
  end
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/ideas/_form.html.erb
<%= form_for(@idea) do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing idea</h1>

<%= render 'form' %>

<%= link_to 'Cancel', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<h1>Listing ideas</h1>

<table width='100%'>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Votes</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.title %></td>
        <td><%= idea.description %></td>
        <td><%= idea.votes.to_i %></td>
        <td><%= idea.user.email %></td>
        <td><%= link_to 'Show', idea %></td>
        <td><%= link_to_if(idea.user.can_edit?(current_user), 'Edit', edit_idea_path(idea)) %></td>
        <td><%= link_to_if(idea.user.can_edit?(current_user), 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' }) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Idea', new_idea_path %>

app/views/ideas/new.html.erb
<h1>New idea</h1>

<%= render 'form' %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @idea.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @idea.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @idea.user.email %>
</p>

<p>
  <strong>Votes:</strong>
  <%= pluralize @idea.votes, "vote" %>
</p>

<div>
  <!-- Todo: don't allow to edit if it's the owner -->
 <!-- % if current_user && current_user.can_vote_for?(@idea) % -->

  <% if current_user && !@idea.user.can_edit?(current_user) %>
    <%= form_tag(vote_idea_path(@idea)) do %>
      <div style="width: 10%">
        <%= number_field_tag :voting_score, @idea_vote.value, in: 0..3 %>
      </div>
      <%= submit_tag "Rate" %>
    <% end %>
  <% end %>
</div>

<br>

<p>
  <% if current_user && @idea.user.can_edit?(current_user) %>
    <%= link_to 'Edit', edit_idea_path(@idea) %> |
  <% end %>
  <%= link_to 'Back', ideas_path %>
</p>

app/views/layouts/_navigation.html.erb
<nav class="top-bar">
  <ul class="title-area">
    <li class="name">
	   <h1><%= link_to "Vote 4 Me", ideas_path %></h1>
    </li>
	</ul>
	<section class="top-bar-section">
    <ul class="left">
      <li class="divider"></li>
      <li><%= link_to "Ideas", ideas_path %></li>
      <li class="divider"></li>
      <li><%= link_to "Add Idea", new_idea_path %></li>
      <li class="divider"></li>
    </ul>
	  <ul class="right">
	    <li class="divider"></li>
	    <% if user_signed_in? %>
        <li style="color: #fff"> Logged in as <strong><%= current_user.email %></strong></li>
        <li class="divider"></li>
        <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
         <li class="divider"></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Sign up", new_user_registration_path %></li>
         <li class="divider"></li>
        <li><%= link_to "Login", new_user_session_path %></li>
      <% end %>
	 </ul>
	</section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />
  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
  	<title><%= content_for?(:title) ? yield(:title) : "Vote4Me" %></title>
  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= render 'layouts/navigation' %>

    <div class="row">
      <div class="large-12 columns">
        <%= display_flash_messages %>
        <%= yield %>
      </div>
    </div>

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>